# Generated by Django 4.2.1 on 2023-06-14 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0003_rename_first_name_user_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
