# Generated by Django 4.2.1 on 2023-07-28 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_ticket_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='note',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
